CREATE OR REPLACE TABLE agrosantanadb.clean.fct_sales as
SELECT 
    NUMERO_INTERNO as id_venta,
    NUMERO_DE_DOCUMENTO as id_documento,
    CODIGO_DE_CLIENTEPROVEEDOR as id_cliente,
    NUMERO_DE_ARTICULO as id_producto,
    FECHA_DE_CONTABILIZACION as fecha_venta,
    hora_de_creacion__incl_segundos as hora_venta,
    NORMA_DE_REPARTO as numero_sucursal,
    NOMBRE_DE_GRUPO as segmento_cliente,
    NOMBRE_DE_CLIENTEPROVEEDOR as nombre_cliente,
    NOMBRE as nombre_factura,
    NIT as numero_identificacion,
    DIRECCION,
    DEPARTAMENTO,
    MUNICIPIO,
    ZONA,
    NOMBRE_DE_EMPLEADO_DEL_DEPARTAMENTO_DE_VENTAS as nombre_trabajador,
    REPLACE(SALDO, ',', '') as saldo_pendiente,
    CODIGO_DE_CONDICIONES_DE_PAGO as plazo_credito,
    NOMBRE_DE_SERIE as tipo_documento,
    CANCELADO as fallo_documento,
    DESCRIPCION_ARTICULOSERV as nombre_producto,
    NOMBRE_DE_GRUPO1 as categoria_producto,
    NOMBRE_DEL_FABRICANTE as subcategoria_producto,
    REPLACE(CANTIDAD, ',', '') as cantidad_ordenada,
    REPLACE(PRECIO_BRUTO_DESPUES_DEL_DESCUENTO, ',', '') as precio_unitario_IVA,
    REPLACE(PRECIO_TRAS_EL_DESCUENTO, ',', '') as precio_unitario_sin_IVA,
    REPLACE(COSTO_DEL_ARTICULO, ',', '') as costo_unitario_sin_IVA,
    REPLACE(GANANCIA_BRUTA, ',', '') as ganacia_sinIVA,
    REPLACE(TOTAL_LINEAIVA, ',', '') as total_venta_IVA,
    REPLACE(TOTAL_LINEA__IVA, ',', '') as total_venta_sin_IVA,
    _DE_DESCUENTO_PARA_DOCUMENTO as porcentaje_descuento,
    year(fecha_de_contabilizacion) as year,
    quarter(fecha_de_contabilizacion) as quarter,
    month(fecha_de_contabilizacion)as month,
    day(fecha_de_contabilizacion) as day,
    week(fecha_de_contabilizacion) as week,
    (regexp_substr(CODIGO_DE_CONDICIONES_DE_PAGO, '[0-9]{1,3}'))::number as indice_plazo_credito
    
FROM agrosantanadb.raw.sales_transactions
where cancelado = FALSE
